# Generated by Django 3.2.10 on 2022-02-23 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(blank=True, null=True, upload_to='')),
                ('training_status', models.PositiveSmallIntegerField(choices=[(0, 'waiting submission'), (1, 'running'), (2, 'complete')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
