# Generated by Django 3.2.10 on 2022-02-23 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(default=uuid.UUID('eae1d960-98e6-4263-975e-85c873b3243d')),
        ),
        migrations.CreateModel(
            name='CharacterSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=1)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'literal')},
            },
        ),
    ]
