# Generated by Django 3.2.10 on 2022-02-23 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220223_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(default=uuid.UUID('3564bbdb-7c44-458a-b314-4316a877b518')),
        ),
    ]
