# Generated by Django 3.2.10 on 2022-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersign',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
