# Generated by Django 3.2.10 on 2022-05-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_charactersign_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersign',
            old_name='image',
            new_name='file',
        ),
    ]
